---
extends:
    - eslint:recommended
    - plugin:prettier/recommended
    - plugin:prettier-doc/recommended
    - plugin:jest/recommended
plugins:
    - import
root: true
env:
    es6: true
    node: true
    jest: true
parserOptions:
    ecmaVersion: 2017
    sourceType: module
rules:
    curly: error
    import/no-extraneous-dependencies:
        - error
        - devDependencies: ["tests*/**", "scripts/**"]
    no-else-return: error
    no-inner-declarations: error
    no-unneeded-ternary: error
    no-debugger: off
    no-unused-vars: off
    no-console: off
    no-useless-return: error
    no-var: error
    one-var:
        - error
        - never
    prefer-arrow-callback: error
    prefer-const: error
    prettier-doc/no-concat: error
    react/no-deprecated: off
    strict: off
    symbol-description: error
    yoda:
        - error
        - never
        - exceptRange: true
overrides:
    - files: "tests/**/*.js"
      rules:
          strict: off
      globals:
          run_spec: true
